version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'com.paritytrading.philadelphia:*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'com.puppycrawl.tools:checkstyle'
        update-types: ['version-update:semver-major']
      - dependency-name: 'org.junit.jupiter:junit-jupiter'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
